### PR TITLE
Fix some handler removal. Only propagate crud terminator events on le…

### LINKED ISSUE #573: Ensure specific events aren't duplicated in raft cluster
* fabric.circuits - unique to each controller
* fabric.links - some overlap, probably unavoidable. Will be addressed if/when we move more link mgmt to routers 
* fabric.routers - about ctrl <-> router connection, so will likely be similar but not identical across controllers
* fabric.terminators - create/update/delete events should only happen from leader by default
* metrics and fabric.usage - first controller to receive propagates 
* services - different per controller. will need to be aggregated externally like usage
* edge.entityCounts - only generate on leader by default
* edge.sessions/edge.apiSessions - TBD, likely going away

### PR DESCRIPTION
**Pull request by plorenz**
…ader by default. Fixes #573

### CODE REVIEW

File: controller/command/command.go [hunk 1]
```diff
@@ -43,13 +43,18 @@ type Validatable interface {
 // system is the leader, apply it locally
 type Dispatcher interface {
 	Dispatch(command Command) error
+	IsLeaderOrLeaderless() bool
```
Comment (andrewpmartinez) [inline controller/command/command.go:46]: This naming could imply that being a leader is different than being leaderless. 

Just curious what the paths are to becoming leaderless. Is it just that an existing leader can go offline?

File: events/dispatcher_terminator.go [hunk 2]
```diff
@@ -45,14 +54,29 @@ func (self *Dispatcher) AcceptTerminatorEvent(event *event.TerminatorEvent) {
...
 
-	self.AddTerminatorEventHandler(handler)
+	propagateAlways := false
+	if val, found := options["propagateAlways"]; found {
+		if b, ok := val.(bool); ok {
+			propagateAlways = b
+		} else if s, ok := val.(string); ok {
+			propagateAlways = strings.EqualFold(s, "true")
+		} else {
+			return errors.New("invalid value for propagateAlways, must be boolean or string")
```
Comment (andrewpmartinez) [inline events/dispatcher_terminator.go:71]: String?

**Review by andrewpmartinez — APPROVED** [review]

File: controller/command/command.go (hunk 1 above)
Comment (plorenz) [reply controller/command/command.go:46]: Yes, I just wanted to account for a state where a leader had gone offline or we were in the middle of an election for anyreason. I figured occasional extra events were better than occasional missed events.
